name: quiz_levels_clean
description: "Quiz app with levels, clean architecture, Riverpod, offline JSON, Lottie, SFX."
publish_to: "none"
version: 8.4.0+13

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  lottie: ^3.1.2
  just_audio: ^0.9.39
  audio_session:
  shared_preferences:
  animate_do:
  url_launcher:
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/haj_questions.json
    - assets/levels_questions.json
    - assets/lottie/
    - assets/sfx/
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700

